web: uvicorn main:app --host 0.0.0.0 --port $PORT
worker: celery -A scheduler.celery_app:celery_app worker --loglevel=INFO --concurrency=2
beat: celery -A scheduler.celery_app:celery_app beat --loglevel=INFO
